### ISSUE TITLE
I can not reproduce your results by using the uploaded checkpoints

### ISSUE THREAD

**Issue by sunchengyi** [arimousa/DDAD#23] opened 2024-02-20 07:39 UTC
I am trying to reproduce the results by using the uploaded checkpoints on hazelnut and screw and can not get the same scores.

For hazelnut the output is as follows:  
Class:  hazelnut   w: 5    v: 1    load_chp: 2000    feature extractor: wide_resnet101_2          w_DA:  3          DLlambda:  0.1
config.model.test_trajectoy_steps=250 , config.data.test_batch_size=16
Detecting Anomalies...
AUROC: (99.4,98.3)
PRO: 87.1 

For screw, it is:  
Class:  screw    w: 2    v: 1    load_chp: 2000    feature extractor: wide_resnet101_2          w_DA:  3          DLlambda:  0.1
config.model.test_trajectoy_steps=250 , config.data.test_batch_size=16
Detecting Anomalies...
AUROC: (96.5,99.3)
PRO: 96.5

It seems that Pixel_AUROC and PRO are similar to your results, but Image_AUROC is very different.
Is there something wrong?
I just ran the code by using the checkpoints. My Python is 3.10 and torch is 2.0.1.

**Comment by arimousa** [comment] 2024-02-20 22:15
I'm uncertain if this could be the cause, but could you please switch the Python version to 3.8 and rerun the code?

**Comment by sunchengyi** [comment] 2024-02-21 07:16
Thank you for the reply. I will try it.
Actually, I have tried other AD models, too, and can not get the same scores as in papers,
particularly when I trained the models myself. However, on MVTecAD, I got the best scores from DDAD by training them myself.
Thank you very much! Great Work!

**Comment by arimousa** [comment] 2024-02-21 14:04
Glad to hear that.
Then I will close the issue.

**Closed as completed by arimousa** 2024-02-21 14:04 UTC
